---
#DEPLOYMENT CONFIG
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: __APP_NAME__
  namespace: __APP_NAMESPACE__
spec:
  selector:
    app: __APP_NAME__
  replicas: 1
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      containers:
        - name: __APP_NAME__
          image: "__DOCKER_SERVER__/__APP_NAMESPACE__/__DOCKER_IMAGE__:__buildNumber__"
          env:
            - name: SAU_PP_HOST
              valueFrom:
                secretKeyRef:
                  name: endpoint-sau
                  key: sau-pp-endpoint
              envFrom:
                secretRef:
                  name: endpoint-sau
            - name: SAU_PGI_HOST
              valueFrom:
                secretKeyRef:
                  name: endpoint-sau
                  key: sau-pgi-endpoint
              envFrom:
                secretRef:
                  name: endpoint-sau
          ports:
            - containerPort: 8080
              protocol: TCP

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  namespace: __APP_NAMESPACE__
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: __APP_NAME__
  type: NodePort

---
# ROUTE
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: __APP_NAME__
  namespace: __APP_NAMESPACE__
spec:
  host: __HOSTNAME__
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: __APP_NAME__
    weight: 100
  wildcardPolicy: None