
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__
  namespace: __APP_NAMESPACE__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: __APP_NAME__
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      containers:
        - name: __APP_NAME__
          image: "__DOCKER_SERVER__/__APP_NAMESPACE__/__DOCKER_IMAGE__:__buildNumber__"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  namespace: __APP_NAMESPACE__
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: __APP_NAME__
  type: NodePort

---
# ROUTE
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: __APP_NAME__
  namespace: __APP_NAMESPACE__
spec:
  host: __HOSTNAME__
  port:
    targetPort: http
  to:
    kind: Service
    name: __APP_NAME__
    weight: 100
  wildcardPolicy: None


